######################################################################
# Automatically generated by qmake (2.01a) Mon Jun 11 11:34:00 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += binaryclockreader.h binarydigit.h
SOURCES += binaryclockreader.cpp binarydigit.cpp main.cpp
RESOURCES += binaryclockreader.qrc
