#############################################################################
# Makefile for building: binaryclockreader
# Generated by qmake (2.01a) (Qt 4.2.2) on: Mon Jun 11 11:34:00 2012
# Project:  binaryclockreader.pro
# Template: app
# Command: /home/zex/pkg/app/qtopia-core-opensource-src-4.2.2/bin/qmake -unix -o Makefile binaryclockreader.pro
#############################################################################

####### Compiler, tools and options

CC            = arm-linux-gcc
CXX           = arm-linux-g++
LEX           = flex
YACC          = yacc
DEFINES       = -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT  $(DEFINES)
CXXFLAGS      = -pipe -O2 -Wall -W -D_REENTRANT  $(DEFINES)
LEXFLAGS      = 
YACCFLAGS     = -d
INCPATH       = -I/usr/Qtopia/mkspecs/qws/linux-arm-g++ -I. -I/usr/Qtopia/include/QtCore -I/usr/Qtopia/include/QtCore -I/usr/Qtopia/include/QtNetwork -I/usr/Qtopia/include/QtNetwork -I/usr/Qtopia/include/QtGui -I/usr/Qtopia/include/QtGui -I/usr/Qtopia/include -I. -I. -I.
LINK          = arm-linux-g++
LFLAGS        = -Wl,-rpath,/usr/Qtopia/lib
LIBS          = $(SUBLIBS)  -L/usr/Qtopia/lib -lQtGui -L/home/zex/pkg/app/qtopia-core-opensource-src-4.2.2/lib -lts -lQtNetwork -lQtCore -lm -ldl -lpthread
AR            = arm-linux-ar cqs
RANLIB        = arm-linux-ranlib
QMAKE         = /home/zex/pkg/app/qtopia-core-opensource-src-4.2.2/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -R
INSTALL_FILE  = $(COPY_FILE)
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = $(COPY_FILE)
DEL_FILE      = rm -f
SYMLINK       = ln -sf
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = binaryclockreader.cpp \
		binarydigit.cpp \
		main.cpp moc_binaryclockreader.cpp \
		moc_binarydigit.cpp \
		qrc_binaryclockreader.cpp
OBJECTS       = binaryclockreader.o \
		binarydigit.o \
		main.o \
		moc_binaryclockreader.o \
		moc_binarydigit.o \
		qrc_binaryclockreader.o
DIST          = /usr/Qtopia/mkspecs/qconfig.pri \
		/usr/Qtopia/mkspecs/features/qt_functions.prf \
		/usr/Qtopia/mkspecs/features/qt_config.prf \
		/usr/Qtopia/mkspecs/features/exclusive_builds.prf \
		/usr/Qtopia/mkspecs/features/default_pre.prf \
		/usr/Qtopia/mkspecs/features/release.prf \
		/usr/Qtopia/mkspecs/features/default_post.prf \
		/usr/Qtopia/mkspecs/features/warn_on.prf \
		/usr/Qtopia/mkspecs/features/qt.prf \
		/usr/Qtopia/mkspecs/features/unix/thread.prf \
		/usr/Qtopia/mkspecs/features/moc.prf \
		/usr/Qtopia/mkspecs/features/resources.prf \
		/usr/Qtopia/mkspecs/features/uic.prf \
		binaryclockreader.pro
QMAKE_TARGET  = binaryclockreader
DESTDIR       = 
TARGET        = binaryclockreader

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: binaryclockreader.pro  /usr/Qtopia/mkspecs/qws/linux-arm-g++/qmake.conf /usr/Qtopia/mkspecs/qconfig.pri \
		/usr/Qtopia/mkspecs/features/qt_functions.prf \
		/usr/Qtopia/mkspecs/features/qt_config.prf \
		/usr/Qtopia/mkspecs/features/exclusive_builds.prf \
		/usr/Qtopia/mkspecs/features/default_pre.prf \
		/usr/Qtopia/mkspecs/features/release.prf \
		/usr/Qtopia/mkspecs/features/default_post.prf \
		/usr/Qtopia/mkspecs/features/warn_on.prf \
		/usr/Qtopia/mkspecs/features/qt.prf \
		/usr/Qtopia/mkspecs/features/unix/thread.prf \
		/usr/Qtopia/mkspecs/features/moc.prf \
		/usr/Qtopia/mkspecs/features/resources.prf \
		/usr/Qtopia/mkspecs/features/uic.prf \
		/usr/Qtopia/lib/libQtGui.prl \
		/usr/Qtopia/lib/libQtCore.prl \
		/usr/Qtopia/lib/libQtNetwork.prl
	$(QMAKE) -unix -o Makefile binaryclockreader.pro
/usr/Qtopia/mkspecs/qconfig.pri:
/usr/Qtopia/mkspecs/features/qt_functions.prf:
/usr/Qtopia/mkspecs/features/qt_config.prf:
/usr/Qtopia/mkspecs/features/exclusive_builds.prf:
/usr/Qtopia/mkspecs/features/default_pre.prf:
/usr/Qtopia/mkspecs/features/release.prf:
/usr/Qtopia/mkspecs/features/default_post.prf:
/usr/Qtopia/mkspecs/features/warn_on.prf:
/usr/Qtopia/mkspecs/features/qt.prf:
/usr/Qtopia/mkspecs/features/unix/thread.prf:
/usr/Qtopia/mkspecs/features/moc.prf:
/usr/Qtopia/mkspecs/features/resources.prf:
/usr/Qtopia/mkspecs/features/uic.prf:
/usr/Qtopia/lib/libQtGui.prl:
/usr/Qtopia/lib/libQtCore.prl:
/usr/Qtopia/lib/libQtNetwork.prl:
qmake:  FORCE
	@$(QMAKE) -unix -o Makefile binaryclockreader.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/binaryclockreader1.0.0 || $(MKDIR) .tmp/binaryclockreader1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/binaryclockreader1.0.0/ && $(COPY_FILE) --parents binaryclockreader.h binarydigit.h .tmp/binaryclockreader1.0.0/ && $(COPY_FILE) --parents binaryclockreader.qrc .tmp/binaryclockreader1.0.0/ && $(COPY_FILE) --parents binaryclockreader.cpp binarydigit.cpp main.cpp .tmp/binaryclockreader1.0.0/ && (cd `dirname .tmp/binaryclockreader1.0.0` && $(TAR) binaryclockreader1.0.0.tar binaryclockreader1.0.0 && $(COMPRESS) binaryclockreader1.0.0.tar) && $(MOVE) `dirname .tmp/binaryclockreader1.0.0`/binaryclockreader1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/binaryclockreader1.0.0


yaccclean:
lexclean:
clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


/usr/Qtopia/bin/moc:
	(cd $(QTDIR)/src/tools/moc && $(MAKE))

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_binaryclockreader.cpp moc_binarydigit.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_binaryclockreader.cpp moc_binarydigit.cpp
moc_binaryclockreader.cpp: binarydigit.h \
		binaryclockreader.h \
		/usr/Qtopia/bin/moc
	/usr/Qtopia/bin/moc $(DEFINES) $(INCPATH) binaryclockreader.h -o moc_binaryclockreader.cpp

moc_binarydigit.cpp: binarydigit.h \
		/usr/Qtopia/bin/moc
	/usr/Qtopia/bin/moc $(DEFINES) $(INCPATH) binarydigit.h -o moc_binarydigit.cpp

compiler_rcc_make_all: qrc_binaryclockreader.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_binaryclockreader.cpp
qrc_binaryclockreader.cpp: binaryclockreader.qrc \
		/usr/Qtopia/bin/rcc \
		img/40x40/normalBinary.png \
		img/40x40/checkedBinary.png
	/usr/Qtopia/bin/rcc -name binaryclockreader binaryclockreader.qrc -o qrc_binaryclockreader.cpp

compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_clean: compiler_moc_header_clean compiler_rcc_clean compiler_image_collection_clean compiler_moc_source_clean compiler_uic_clean 

####### Compile

binaryclockreader.o: binaryclockreader.cpp binaryclockreader.h \
		binarydigit.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o binaryclockreader.o binaryclockreader.cpp

binarydigit.o: binarydigit.cpp binarydigit.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o binarydigit.o binarydigit.cpp

main.o: main.cpp binaryclockreader.h \
		binarydigit.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

moc_binaryclockreader.o: moc_binaryclockreader.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_binaryclockreader.o moc_binaryclockreader.cpp

moc_binarydigit.o: moc_binarydigit.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_binarydigit.o moc_binarydigit.cpp

qrc_binaryclockreader.o: qrc_binaryclockreader.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_binaryclockreader.o qrc_binaryclockreader.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

